.TH "main.c" 3 "Fri Sep 9 2022" "Version 0.0.1" "perroquet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'crypt\&.h'\fP
.br
\fC#include 'interface\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBargp_program_bug_address\fP = 'boukhatem\&.abderraouf@gmail\&.com'"
.br
.ti -1c
.RI "const char * \fBargp_program_version\fP = '0\&.0\&.1'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 9 of file main\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const char* argp_program_bug_address = 'boukhatem\&.abderraouf@gmail\&.com'"

.PP
Definition at line 6 of file main\&.c\&.
.SS "const char* argp_program_version = '0\&.0\&.1'"

.PP
Definition at line 7 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for perroquet from the source code\&.
